title: "BufとProtobufで始めるモダンgRPC開発"
summary: "Protocol Buffers(Protobuf)を用いた開発(主にgRPC)にはprotocのようなコンパイラが長い間使われてきました。
  コード生成やドキュメントの作成、REST APIとしてのゲートウェイの実装など便利で柔軟なprotocプラグインが利用できる一方、そのためのコード生成コマンドは複雑になりがちです。
  こういったProtobufを用いた開発に関わるさまざまな問題をBufは解決するためにBuf CLIやBuf Schema Registry、Connectプロトコルなどさまざまなツールやプロトコルを開発しました。
  本書ではBufが開発したさまざまなツールやプロトコルを使用し、現代的でモダンなProtobuf開発について紹介します。"
topics: ["gRPC", "Buf", "ProtocolBuffers", "Connect", "Go"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "1" # はじめに
  - "2" # 本書を読むための事前知識
  - "3" # BufについてとBuf CLIのインストール
  - "4" # Buf Lintを使ってprotoファイルをLintする
  - "5" # Buf Formatを使ってprotoファイルをフォーマットする
  - "6" # Buf Breakingを使って破壊的変更を検知する
  - "7" # Buf CLIを使ってgRPCサーバーを実装する
  - "8" # Buf Curlを使用してgRPCサーバーと通信する
  - "9" # BSRを使ってProtobufモジュールを公開する
  - "10" # Connectを使って公開したモジュールで通信する
  - "11" # BufをCI/CD環境で使用する
  - "12" # おわりに

