title: "古典学派的テストとGoで考える持続可能なアーキテクチャ入門"
summary: "「単体テストの考え方/使い方」という書籍の中でテストの書き方により「古典学派」と「ロンドン学派」に分けられるということが書かれています。

  現代の開発現場ではモックを使用したロンドン学派的なテストを書くためにも依存性の逆転を使用したクリーンアーキテクチャのようなアーキテクチャが採用されるケースが多くなってきたなと感じます。


  この本ではモックを極力しようしない古典学派的なテストの書き方にこだわったアーキテクチャをGoを使用して再考していきたいと思います。"
topics: ["Go", "test", "integration", "e2e", "golang"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
  - chapter8
  - chapter9
  - chapter10
  - chapter11
  - chapter12
  - chapter13
  - chapter14
  - chapter15
  - chapter16
  - chapter17
