title: "[protovalidate徹底ガイド] より安全でドキュメント性の高いスキーマ駆動開発"
summary: "Protobufのスキーマをバリデーションするのに長らくprotoc-gen-validate(PGV)が使われてきました。しかし、PGVはすでにその役目を終えprotovalidateが完全な後継としてその役目を引き継ぐこととなりました。protovalidateはGoogleが開発した式言語であるCEL(Common Expression Language)を採用しており、より柔軟な制約を可能としましたがCELの情報はまだ少なくprotovalidateに難しさを感じた人もいるかもしれません。
  本書籍ではprotovalidateの使い方と全ての制約ルールを解説、紹介するだけでなくCELを使った基本的な評価式の読み書きについて解説することでprotovalidate採用の手助けとなることを目的としています。"
topics: ["protovalidate", "Buf", "Protocolbuffers", "Go", "CEL"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "1" # はじめに
  - "2" # protovalidateについて
  - "3" # protovalidateを使ってみる
  - "4" # message / oneofのバリデーション
  - "5" # stringのバリデーション
  - "6" # bool / bytesのバリデーション
  - "7" # 数値のバリデーション
  - "8" # enumのバリデーション
  - "9" # map / repeatedのバリデーション
  - "10" # Well-Known Typesのバリデーション
  - "11" # FieldConstratinsのその他の値について
  - "12" # CELについてより詳しく知る
  - "13" # (おまけ)protovalidateへのコントリビュート
  - "14" # おわりに